//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action_Log
    {
        public int Action_LogID { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionMessage
    {
        public int ActionID { get; set; }
        public int NextTaskID { get; set; }
        public string Message { get; set; }
        public Nullable<bool> HasCommitteeInfo { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<byte> PhaseID { get; set; }
    
        public virtual WFAction WFAction { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual Task Task { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Application_ActionStatus = new HashSet<Application_ActionStatus>();
            this.Application_Log = new HashSet<Application_Log>();
            this.Application_Messages = new HashSet<Application_Messages>();
            this.Application_Properties = new HashSet<Application_Properties>();
            this.Application_Role = new HashSet<Application_Role>();
            this.Application_TaskForm = new HashSet<Application_TaskForm>();
            this.Application_TaskFormExt = new HashSet<Application_TaskFormExt>();
            this.Form_DepartmentCommittee = new HashSet<Form_DepartmentCommittee>();
            this.Form_AttachmentAd = new HashSet<Form_AttachmentAd>();
            this.Form_ExtRev = new HashSet<Form_ExtRev>();
            this.Form_FinalExtRev = new HashSet<Form_FinalExtRev>();
            this.Form_FinalPC = new HashSet<Form_FinalPC>();
            this.Form_MeetingMembers = new HashSet<Form_MeetingMembers>();
            this.Form_Meetings = new HashSet<Form_Meetings>();
            this.Form_Voting = new HashSet<Form_Voting>();
            this.Form_PointChanges = new HashSet<Form_PointChanges>();
            this.Form_Points = new HashSet<Form_Points>();
            this.Form_PromotionCommittee = new HashSet<Form_PromotionCommittee>();
            this.PublicationsEvaluations = new HashSet<PublicationsEvaluation>();
            this.Evaluations = new HashSet<Evaluation>();
            this.Form_Refree = new HashSet<Form_Refree>();
            this.SentEmails = new HashSet<SentEmail>();
            this.Application_TaskLog = new HashSet<Application_TaskLog>();
        }
    
        public int ApplicationID { get; set; }
        public bool ApplicationClosed { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<byte> PhaseID { get; set; }
        public string ForRank { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> ExclusionList { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> HardCopy { get; set; }
        public string SCComments { get; set; }
        public bool RectorDecision { get; set; }
        public bool FinalDeicision { get; set; }
        public bool SCDecision { get; set; }
        public string RectorComments { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_ActionStatus> Application_ActionStatus { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Log> Application_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Messages> Application_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Properties> Application_Properties { get; set; }
        public virtual Form_Checklist Form_Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Role> Application_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskForm> Application_TaskForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskFormExt> Application_TaskFormExt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_DepartmentCommittee> Form_DepartmentCommittee { get; set; }
        public virtual Form_AppProperties Form_AppProperties { get; set; }
        public virtual Form_AreaOfSp Form_AreaOfSp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_AttachmentAd> Form_AttachmentAd { get; set; }
        public virtual Form_ChairmanInput Form_ChairmanInput { get; set; }
        public virtual Form_CollegeInput Form_CollegeInput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_ExtRev> Form_ExtRev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_FinalExtRev> Form_FinalExtRev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_FinalPC> Form_FinalPC { get; set; }
        public virtual Form_MaterialFlag Form_MaterialFlag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_MeetingMembers> Form_MeetingMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_Meetings> Form_Meetings { get; set; }
        public virtual Form_PCFeedback Form_PCFeedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_Voting> Form_Voting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_PointChanges> Form_PointChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_Points> Form_Points { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_PromotionCommittee> Form_PromotionCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicationsEvaluation> PublicationsEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_Refree> Form_Refree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentEmail> SentEmails { get; set; }
        public virtual Form_ServiceYears Form_ServiceYears { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskLog> Application_TaskLog { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_ActionStatus
    {
        public int ApplicationID { get; set; }
        public int ActionID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual WFAction WFAction { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Log
    {
        public int LogID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string Message { get; set; }
        public string Comments { get; set; }
        public string Details { get; set; }
        public string Actor { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual WFAction WFAction { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_LogExt
    {
        public int logID { get; set; }
        public int ApplicationID { get; set; }
        public string ExtActionTitle { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Messages
    {
        public int MessageID { get; set; }
        public int ApplicationID { get; set; }
        public string FromRole { get; set; }
        public string ToRole { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public string Message { get; set; }
        public string SendDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Properties
    {
        public int PropertyID { get; set; }
        public int ApplicationID { get; set; }
        public string Property { get; set; }
        public string Value { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Role
    {
        public int ApplicationID { get; set; }
        public byte RoleID { get; set; }
        public string EmployeeID { get; set; }
        public int ExternalEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string IsActing { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ExternalEmployee ExternalEmployee { get; set; }
        public virtual Role Role { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_TaskForm
    {
        public int ApplicationID { get; set; }
        public int TaskID { get; set; }
        public byte FormID { get; set; }
        public bool Completed { get; set; }
        public string Message { get; set; }
        public bool TaskExternal { get; set; }
        public int ExternalReviewerID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Form Form { get; set; }
        public virtual Task Task { get; set; }
        public virtual ExternalReviewer ExternalReviewer { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_TaskFormExt
    {
        public int ApplicationID { get; set; }
        public int TaskID { get; set; }
        public byte FormID { get; set; }
        public bool Completed { get; set; }
        public string Message { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Form Form { get; set; }
        public virtual Task_Ext Task_Ext { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_TaskLog
    {
        public int TaskLogID { get; set; }
        public int ApplicationID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public bool Completed { get; set; }
        public Nullable<int> Reminders { get; set; }
        public string Message { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Task Task { get; set; }
        public virtual WFAction WFAction { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_TaskLogExt
    {
        public int TaskLogID { get; set; }
        public int ApplicationID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public bool Completed { get; set; }
        public int Reminders { get; set; }
        public string EmailAddress { get; set; }
        public int ExternalReviewerID { get; set; }
        public string Message { get; set; }
        public string EmployeeID { get; set; }
        public int ExternalEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ExternalEmployee ExternalEmployee { get; set; }
        public virtual Task_Ext Task_Ext { get; set; }
        public virtual ExternalReviewer ExternalReviewer { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationChecklist
    {
        public int ApplicationID { get; set; }
        public Nullable<bool> Field1Status { get; set; }
        public string Field1Comments { get; set; }
        public Nullable<bool> Field2Status { get; set; }
        public string Field2Comments { get; set; }
        public Nullable<bool> Field3Status { get; set; }
        public string Field3Comments { get; set; }
        public Nullable<bool> Field4Status { get; set; }
        public string Field4Comments { get; set; }
        public Nullable<bool> Field5Status { get; set; }
        public string Field5Comments { get; set; }
        public Nullable<bool> Field6Status { get; set; }
        public string Field6Comments { get; set; }
        public Nullable<bool> Field7Status { get; set; }
        public string Field7Comments { get; set; }
        public Nullable<bool> Field8Status { get; set; }
        public string Field8Comments { get; set; }
        public Nullable<bool> OverallStatus { get; set; }
        public string Remarks { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttachmentCategory()
        {
            this.Form_Attachment = new HashSet<Form_Attachment>();
            this.Form_AttachmentAd = new HashSet<Form_AttachmentAd>();
        }
    
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_Attachment> Form_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_AttachmentAd> Form_AttachmentAd { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedPromotionCommittee
    {
        public int ApplicationID { get; set; }
        public Nullable<bool> isKFUPM { get; set; }
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Rank { get; set; }
        public string Email { get; set; }
        public string MailingAddress { get; set; }
        public string Major { get; set; }
        public int id { get; set; }
        public string Phone { get; set; }
        public string WLStatus { get; set; }
        public string Comments { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Departments1 = new HashSet<Department>();
            this.Employees = new HashSet<Employee>();
        }
    
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> ParentDeptID { get; set; }
        public string HeadEmpID { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<byte> HeadRoleID { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string DeputyEmail { get; set; }
        public string NameString { get; set; }
        public string HeadString { get; set; }
        public string ParentDeptString { get; set; }
        public string HeadEmail { get; set; }
        public string NameAr { get; set; }
        public string NameStringAr { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Deputy2Email { get; set; }
        public string Website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments1 { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentManager
    {
        public byte RoleID { get; set; }
        public string Department { get; set; }
        public string EmployeeID { get; set; }
        public string DeputyEmployeeID { get; set; }
        public string DeputyEmail { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtproperty
    {
        public int id { get; set; }
        public Nullable<int> objectid { get; set; }
        public string property { get; set; }
        public string value { get; set; }
        public string uvalue { get; set; }
        public byte[] lvalue { get; set; }
        public int version { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Admins = new HashSet<Admin>();
            this.Applications = new HashSet<Application>();
            this.Application_Role = new HashSet<Application_Role>();
            this.Application_TaskLogExt = new HashSet<Application_TaskLogExt>();
            this.Departments = new HashSet<Department>();
            this.Evaluations = new HashSet<Evaluation>();
            this.Form_AttachmentAd = new HashSet<Form_AttachmentAd>();
            this.Form_FinalPC = new HashSet<Form_FinalPC>();
            this.Form_PromotionCommittee = new HashSet<Form_PromotionCommittee>();
            this.Form_Voting = new HashSet<Form_Voting>();
            this.PermanentCommittees = new HashSet<PermanentCommittee>();
        }
    
        public string EmployeeID { get; set; }
        public string SecondEmail { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string Department { get; set; }
        public string ParentDept { get; set; }
        public string POBox { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string NameString { get; set; }
        public string Specialty { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Password { get; set; }
        public string Major { get; set; }
        public string DeptShort { get; set; }
        public string Name_1 { get; set; }
        public string Name_2 { get; set; }
        public string Name_3 { get; set; }
        public string Name_4 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string ContractType { get; set; }
        public string Mobile { get; set; }
        public string Pager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin> Admins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Role> Application_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskLogExt> Application_TaskLogExt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Department Department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_AttachmentAd> Form_AttachmentAd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_FinalPC> Form_FinalPC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_PromotionCommittee> Form_PromotionCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_Voting> Form_Voting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermanentCommittee> PermanentCommittees { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExt
    {
        public string EmployeeID { get; set; }
        public string SecondEmail { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string Department { get; set; }
        public string College { get; set; }
        public string POBox { get; set; }
        public string Phone { get; set; }
        public string JoinDate { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluation
    {
        public int QuestionID { get; set; }
        public Nullable<int> QNo { get; set; }
        public string Title { get; set; }
        public string QText { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> ARBVisible { get; set; }
        public string ARBTitle { get; set; }
        public string ARBOption { get; set; }
        public string ARBValue { get; set; }
        public Nullable<bool> ACBVisible { get; set; }
        public string ACBTitle { get; set; }
        public string ACBOption { get; set; }
        public string ACBValue { get; set; }
        public Nullable<bool> ADDLVisible { get; set; }
        public string ADDLTitle { get; set; }
        public string ADDLOption { get; set; }
        public Nullable<bool> ADDLRequired { get; set; }
        public string ADDLValue { get; set; }
        public Nullable<bool> ATAVisible { get; set; }
        public string ATATitle { get; set; }
        public string ATAAttribute { get; set; }
        public string ATAStyle { get; set; }
        public Nullable<bool> ATARequired { get; set; }
        public string ATAValue { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> ExternalReviewerID { get; set; }
        public Nullable<bool> AnswerOnSameLine { get; set; }
        public string AnswerInstruction { get; set; }
        public string QuestionWidth { get; set; }
        public string Lang { get; set; }
        public Nullable<int> ExternalEmployeeID { get; set; }
        public string SourceJSON { get; set; }
        public string FormTitle { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ExternalEmployee ExternalEmployee { get; set; }
        public virtual ExternalReviewer ExternalReviewer { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalEmployee()
        {
            this.Application_Role = new HashSet<Application_Role>();
            this.Application_TaskLogExt = new HashSet<Application_TaskLogExt>();
            this.Evaluations = new HashSet<Evaluation>();
            this.Form_FinalPC = new HashSet<Form_FinalPC>();
            this.Form_PromotionCommittee = new HashSet<Form_PromotionCommittee>();
            this.PermanentCommittees = new HashSet<PermanentCommittee>();
        }
    
        public int ExternalEmployeeID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string Department { get; set; }
        public string Organization { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Country { get; set; }
        public string NameString { get; set; }
        public string Status { get; set; }
        public string Password { get; set; }
        public string Major { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Role> Application_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskLogExt> Application_TaskLogExt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_FinalPC> Form_FinalPC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_PromotionCommittee> Form_PromotionCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermanentCommittee> PermanentCommittees { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalReviewer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalReviewer()
        {
            this.Application_TaskForm = new HashSet<Application_TaskForm>();
            this.Application_TaskLogExt = new HashSet<Application_TaskLogExt>();
            this.Evaluations = new HashSet<Evaluation>();
            this.Form_ExtRev = new HashSet<Form_ExtRev>();
            this.Form_FinalExtRev = new HashSet<Form_FinalExtRev>();
            this.PublicationsEvaluations = new HashSet<PublicationsEvaluation>();
        }
    
        public int ExternalReviewerID { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string MailingAddress { get; set; }
        public string Email { get; set; }
        public string Major { get; set; }
        public string Specialty { get; set; }
        public string PhoneAndFax { get; set; }
        public string ActiveAreaOfResearch { get; set; }
        public string PrevAreaOfResearch { get; set; }
        public string Webpage { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TotalPublications { get; set; }
        public Nullable<int> NoOfJournals { get; set; }
        public Nullable<int> HIndex { get; set; }
        public Nullable<int> Citations { get; set; }
        public string SWIFTCode { get; set; }
        public string IBAN { get; set; }
        public string Password { get; set; }
        public string PassportNo { get; set; }
        public string NameString { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Description { get; set; }
        public string NameAr { get; set; }
        public string Name_1 { get; set; }
        public string Name_2 { get; set; }
        public string Name_3 { get; set; }
        public string Name_4 { get; set; }
        public string Salt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskForm> Application_TaskForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskLogExt> Application_TaskLogExt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_ExtRev> Form_ExtRev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_FinalExtRev> Form_FinalExtRev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicationsEvaluation> PublicationsEvaluations { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtFormInstruction
    {
        public byte FormID { get; set; }
        public string Instruction { get; set; }
        public string Type { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.Form_Attachment = new HashSet<Form_Attachment>();
        }
    
        public int FileID { get; set; }
        public string FileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_Attachment> Form_Attachment { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form()
        {
            this.Application_TaskForm = new HashSet<Application_TaskForm>();
            this.Application_TaskFormExt = new HashSet<Application_TaskFormExt>();
            this.FormVariables = new HashSet<FormVariable>();
            this.TaskForms = new HashSet<TaskForm>();
        }
    
        public byte FormID { get; set; }
        public string Title { get; set; }
        public string Page { get; set; }
        public Nullable<bool> AllowFAAction { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> FormCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskForm> Application_TaskForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskFormExt> Application_TaskFormExt { get; set; }
        public virtual ExtFormInstruction ExtFormInstruction { get; set; }
        public virtual FormCategory FormCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormVariable> FormVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskForm> TaskForms { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_AppProperties
    {
        public int ApplicationID { get; set; }
        public string AreaOfSpecialization { get; set; }
        public string PlaceOfGraduation { get; set; }
        public string Degree { get; set; }
        public Nullable<System.DateTime> DateOfGraduation { get; set; }
        public Nullable<System.DateTime> DateOfAppointment { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<bool> CommnityService { get; set; }
        public Nullable<bool> TeachingLoad { get; set; }
        public string PSubCommConclusion { get; set; }
        public string ReasonsForExemption { get; set; }
        public Nullable<System.DateTime> DateOfPromotion { get; set; }
        public string AppointmentTypeDesc { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_AreaOfSp
    {
        public int ApplicationID { get; set; }
        public string AreaOfSpecialization { get; set; }
        public string PhdFrom { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Attachment
    {
        public int AttachmentID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<byte> RoleID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> SelectionForExtRev { get; set; }
    
        public virtual AttachmentCategory AttachmentCategory { get; set; }
        public virtual File File { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_AttachmentAd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form_AttachmentAd()
        {
            this.PublicationsEvaluations = new HashSet<PublicationsEvaluation>();
        }
    
        public int Form_AttachmentAdID { get; set; }
        public Nullable<int> AttachmentCategoryID { get; set; }
        public int ApplicationID { get; set; }
        public string EmployeeID { get; set; }
        public string DocumentName { get; set; }
        public string DocumentSize { get; set; }
        public Nullable<byte> RoleID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> SelectionForExtRev { get; set; }
        public Nullable<System.DateTime> DateOfPublication { get; set; }
        public string Journal { get; set; }
        public int NoOfAuthors { get; set; }
        public bool FirstAuthor { get; set; }
        public decimal Points { get; set; }
        public string Remarks { get; set; }
        public bool Accept { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public bool Related { get; set; }
        public string Indexing { get; set; }
        public string ImpactFactor { get; set; }
        public string Publisher { get; set; }
        public string DocumentTitle { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AttachmentCategory AttachmentCategory { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicationsEvaluation> PublicationsEvaluations { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_ChairmanInput
    {
        public int ApplicationID { get; set; }
        public string Teaching { get; set; }
        public string Research { get; set; }
        public string CommunityService { get; set; }
        public string CommentsAndRecommendation { get; set; }
        public string MeetingNo { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public string F18 { get; set; }
        public string F19 { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Checklist
    {
        public int ApplicationID { get; set; }
        public string ListID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> OverallStatus { get; set; }
        public string Remarks { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_CollegeInput
    {
        public int ApplicationID { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string MeetingNo { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_DepartmentCommittee
    {
        public int ApplicationID { get; set; }
        public byte Position { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_ExtRev
    {
        public int ApplicationID { get; set; }
        public int Type { get; set; }
        public int Serial { get; set; }
        public int ExternalReviewerID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ExternalReviewer ExternalReviewer { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Feedback
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_FinalExtRev
    {
        public int ApplicationID { get; set; }
        public int ExternalReviewerID { get; set; }
        public Nullable<int> Serial { get; set; }
        public string WLStatus { get; set; }
        public Nullable<System.DateTime> WLDate { get; set; }
        public string CommentsWithWL { get; set; }
        public string MaterialSentStatus { get; set; }
        public Nullable<System.DateTime> MaterialSentDate { get; set; }
        public string EvaluationStatus { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public string CommentsWithEval { get; set; }
        public Nullable<bool> ShowExtRev2PC { get; set; }
        public Nullable<bool> ShowEval2PC { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Source { get; set; }
        public Nullable<int> EvaluationID { get; set; }
        public string NameString { get; set; }
        public Nullable<bool> PromotionRecom { get; set; }
        public string Reasons { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Form_ReviewersForm Form_ReviewersForm { get; set; }
        public virtual ExternalReviewer ExternalReviewer { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_FinalPC
    {
        public int ApplicationID { get; set; }
        public string EmployeeID { get; set; }
        public int ExternalEmployeeID { get; set; }
        public int Position { get; set; }
        public string WLStatus { get; set; }
        public Nullable<bool> DigitalSignature { get; set; }
        public Nullable<System.DateTime> DSDate { get; set; }
        public string Comments { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> WLDate { get; set; }
        public string CommentsWithWL { get; set; }
        public string Status { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ExternalEmployee ExternalEmployee { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_FinalPromotionCommittee
    {
        public int ApplicationID { get; set; }
        public string Type { get; set; }
        public byte Position { get; set; }
        public int AutoNumberPK { get; set; }
        public Nullable<bool> isKFUPM { get; set; }
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Rank { get; set; }
        public string Email { get; set; }
        public string MailingAddress { get; set; }
        public string Major { get; set; }
        public string WLStatus { get; set; }
        public bool UserAccess { get; set; }
        public Nullable<int> AcknoledgementSend { get; set; }
        public Nullable<bool> DigitalSignature { get; set; }
        public Nullable<System.DateTime> DSDate { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Comments { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_FinalRefree
    {
        public int ApplicationID { get; set; }
        public byte Type { get; set; }
        public byte Serial { get; set; }
        public string Name { get; set; }
        public bool ForwardToPC { get; set; }
        public string Rank { get; set; }
        public string MailingAddress { get; set; }
        public string Email { get; set; }
        public string Major { get; set; }
        public string Speciality { get; set; }
        public string PhoneAndFax { get; set; }
        public string ActiveAreaOfResearch { get; set; }
        public string PrevAreaOfResearch { get; set; }
        public string Webpage { get; set; }
        public string Comments { get; set; }
        public int RefreeID { get; set; }
        public bool PCCommentsSubmit { get; set; }
        public string PCComments { get; set; }
        public string WLStatus { get; set; }
        public Nullable<System.DateTime> DateWL { get; set; }
        public string CommentsWithWL { get; set; }
        public bool UserAccess { get; set; }
        public bool HardCopySent { get; set; }
        public Nullable<bool> EvaluationRecieved { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool PermitPC { get; set; }
        public Nullable<int> TotalPublications { get; set; }
        public Nullable<int> NoOfJournals { get; set; }
        public Nullable<int> HIndex { get; set; }
        public string SWIFTCode { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> Citations { get; set; }
        public string Source { get; set; }
    
        public virtual Form_ReviewersForm Form_ReviewersForm { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_MaterialFlag
    {
        public int ApplicationID { get; set; }
        public Nullable<bool> PCMaterialReady4ExtRevFlag { get; set; }
        public string MaterialOKEmail { get; set; }
        public string MaterialNotOKEmail { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string EmailFromTopAuthority { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_MeetingMembers
    {
        public int MeetingID { get; set; }
        public string MembersID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<System.DateTime> PostingDateTime { get; set; }
        public bool SchedulePostStatus { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Form_Meetings Form_Meetings { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Meetings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form_Meetings()
        {
            this.Form_MeetingMembers = new HashSet<Form_MeetingMembers>();
        }
    
        public int MeetingID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public string Year { get; set; }
        public Nullable<int> TimeSlot1 { get; set; }
        public Nullable<int> TimeSlot2 { get; set; }
        public Nullable<int> TimeSlot3 { get; set; }
        public Nullable<int> TimeSlot4 { get; set; }
        public Nullable<int> TimeSlot5 { get; set; }
        public Nullable<int> TimeSlot6 { get; set; }
        public Nullable<int> TimeSlot7 { get; set; }
        public Nullable<int> TimeSlot8 { get; set; }
        public Nullable<int> TimeSlot9 { get; set; }
        public Nullable<int> TimeSlot10 { get; set; }
        public Nullable<int> TimeSlot11 { get; set; }
        public Nullable<int> TimeSlot12 { get; set; }
        public Nullable<int> TimeSlot13 { get; set; }
        public Nullable<int> TimeSlot14 { get; set; }
        public Nullable<int> TimeSlot15 { get; set; }
        public Nullable<int> TimeSlot16 { get; set; }
        public Nullable<int> TimeSlot17 { get; set; }
        public Nullable<int> TimeSlot18 { get; set; }
        public Nullable<int> TimeSlot19 { get; set; }
        public Nullable<int> TimeSlot20 { get; set; }
        public Nullable<int> TimeSlot21 { get; set; }
        public Nullable<int> TimeSlot22 { get; set; }
        public Nullable<int> TimeSlot23 { get; set; }
        public Nullable<int> TimeSlot24 { get; set; }
        public Nullable<int> TimeSlot25 { get; set; }
        public Nullable<int> TimeSlot26 { get; set; }
        public Nullable<int> TimeSlot27 { get; set; }
        public Nullable<int> TimeSlot28 { get; set; }
        public Nullable<int> TimeSlot29 { get; set; }
        public Nullable<int> TimeSlot30 { get; set; }
        public Nullable<int> TimeSlot31 { get; set; }
        public Nullable<int> TimeSlot32 { get; set; }
        public Nullable<int> TimeSlot33 { get; set; }
        public Nullable<int> TimeSlot34 { get; set; }
        public Nullable<int> TimeSlot35 { get; set; }
        public Nullable<int> TimeSlot36 { get; set; }
        public Nullable<int> TimeSlot37 { get; set; }
        public Nullable<int> TimeSlot38 { get; set; }
        public Nullable<int> TimeSlot39 { get; set; }
        public Nullable<int> TimeSlot40 { get; set; }
        public Nullable<int> TimeSlot41 { get; set; }
        public Nullable<int> TimeSlot42 { get; set; }
        public Nullable<int> TimeSlot43 { get; set; }
        public Nullable<int> TimeSlot44 { get; set; }
        public Nullable<int> TimeSlot45 { get; set; }
        public Nullable<System.DateTime> FinalSelectedTime { get; set; }
        public string FinalSelectedDate { get; set; }
        public bool MeetingStatus { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_MeetingMembers> Form_MeetingMembers { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_PCFeedback
    {
        public int ApplicationID { get; set; }
        public string TP { get; set; }
        public string Prod { get; set; }
        public string QualJ { get; set; }
        public string QualC { get; set; }
        public string Orig { get; set; }
        public string Signi { get; set; }
        public string IR { get; set; }
        public string CR { get; set; }
        public string SS { get; set; }
        public string CU_PS { get; set; }
        public string GenRmrk { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_PointChanges
    {
        public int ApplicationID { get; set; }
        public string CellCode { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Justification { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Points
    {
        public int ApplicationID { get; set; }
        public string Type { get; set; }
        public Nullable<byte> P1a { get; set; }
        public Nullable<byte> P1b { get; set; }
        public Nullable<byte> P1c { get; set; }
        public Nullable<byte> P1d { get; set; }
        public Nullable<byte> P1e { get; set; }
        public Nullable<byte> P1f { get; set; }
        public Nullable<byte> P1g { get; set; }
        public Nullable<byte> P1h { get; set; }
        public Nullable<byte> P1i { get; set; }
        public Nullable<byte> P2a { get; set; }
        public Nullable<byte> P2b { get; set; }
        public Nullable<byte> P2c { get; set; }
        public Nullable<byte> P2d { get; set; }
        public Nullable<byte> P2e { get; set; }
        public Nullable<byte> P2f { get; set; }
        public Nullable<byte> P2g { get; set; }
        public Nullable<byte> P2h { get; set; }
        public Nullable<byte> P2i { get; set; }
        public Nullable<byte> P3a { get; set; }
        public Nullable<byte> P3b { get; set; }
        public Nullable<byte> P3c { get; set; }
        public Nullable<byte> P3d { get; set; }
        public Nullable<byte> P3e { get; set; }
        public Nullable<byte> P3f { get; set; }
        public Nullable<byte> P3g { get; set; }
        public Nullable<byte> P3h { get; set; }
        public Nullable<byte> P3i { get; set; }
        public Nullable<byte> P4a { get; set; }
        public Nullable<byte> P4b { get; set; }
        public Nullable<byte> P4c { get; set; }
        public Nullable<byte> P5d { get; set; }
        public Nullable<byte> P5e { get; set; }
        public Nullable<byte> P5f { get; set; }
        public Nullable<byte> P5g { get; set; }
        public Nullable<byte> P5h { get; set; }
        public Nullable<byte> P5i { get; set; }
        public Nullable<decimal> SumTotal { get; set; }
        public Nullable<decimal> SumSigle { get; set; }
        public Nullable<decimal> SumJournal { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_PromotionCommittee
    {
        public int ApplicationID { get; set; }
        public string Type { get; set; }
        public byte Position { get; set; }
        public Nullable<bool> IsKFUPM { get; set; }
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Rank { get; set; }
        public string Email { get; set; }
        public string MailingAddress { get; set; }
        public string Major { get; set; }
        public string Phone { get; set; }
        public int ExternalEmployeeID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ExternalEmployee ExternalEmployee { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_PromotionReport
    {
        public int ApplicationID { get; set; }
        public string FileName { get; set; }
        public string Comments { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Refree
    {
        public int ApplicationID { get; set; }
        public byte Type { get; set; }
        public byte Serial { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string MailingAddress { get; set; }
        public string Email { get; set; }
        public string Major { get; set; }
        public string Speciality { get; set; }
        public string PhoneAndFax { get; set; }
        public string ActiveAreaOfResearch { get; set; }
        public string PrevAreaOfResearch { get; set; }
        public string Webpage { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TotalPublications { get; set; }
        public Nullable<int> NoOfJournals { get; set; }
        public Nullable<int> HIndex { get; set; }
        public Nullable<int> Citations { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_ReviewersForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form_ReviewersForm()
        {
            this.Form_FinalExtRev = new HashSet<Form_FinalExtRev>();
        }
    
        public int RefreeID { get; set; }
        public int Status { get; set; }
        public string familiarity { get; set; }
        public Nullable<int> Q1 { get; set; }
        public string Q1Justification { get; set; }
        public Nullable<int> Q2 { get; set; }
        public string Q2Justification { get; set; }
        public Nullable<int> Q3 { get; set; }
        public string Q3Justification { get; set; }
        public Nullable<int> Q4 { get; set; }
        public string Q4Justification { get; set; }
        public Nullable<int> Q5 { get; set; }
        public string Q5Justification { get; set; }
        public Nullable<int> Q6 { get; set; }
        public string Q6Justification { get; set; }
        public Nullable<int> Q7 { get; set; }
        public string Q7Justification { get; set; }
        public Nullable<int> Q8 { get; set; }
        public string Q8Justification { get; set; }
        public Nullable<int> Q9 { get; set; }
        public string Q9Justification { get; set; }
        public string Comments { get; set; }
        public string SupDocument { get; set; }
        public string Size { get; set; }
        public Nullable<int> FamiliarityNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_FinalExtRev> Form_FinalExtRev { get; set; }
        public virtual Form_FinalRefree Form_FinalRefree { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_ServiceYears
    {
        public int ApplicationID { get; set; }
        public Nullable<byte> App_Service_NumYears { get; set; }
        public Nullable<byte> App_Service_NumMonths { get; set; }
        public Nullable<byte> App_Saudi_NumYears { get; set; }
        public Nullable<byte> App_Saudi_NumMonths { get; set; }
        public Nullable<byte> Service_NumYears { get; set; }
        public Nullable<byte> Service_NumMonths { get; set; }
        public Nullable<byte> Saudi_NumYears { get; set; }
        public Nullable<byte> Saudi_NumMonths { get; set; }
        public string Evaluations { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<float> TeachingScoreYear1 { get; set; }
        public Nullable<float> TeachingScoreYear2 { get; set; }
        public Nullable<float> ResearchScoreYear1 { get; set; }
        public Nullable<float> ResearchScoreYear2 { get; set; }
        public Nullable<float> ComServiceScoreYear1 { get; set; }
        public Nullable<float> ComServiceScoreYear2 { get; set; }
        public Nullable<int> Year1 { get; set; }
        public Nullable<int> Year2 { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Voting
    {
        public int ApplicationID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> Teaching { get; set; }
        public Nullable<int> Research { get; set; }
        public Nullable<int> Services { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormCategory()
        {
            this.Forms = new HashSet<Form>();
        }
    
        public int FormCategoryID { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form> Forms { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormVariable
    {
        public int FormVariableID { get; set; }
        public byte FormID { get; set; }
        public string Variable { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string ValueString { get; set; }
        public string FormTable { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NameExclusion
    {
        public byte RoleID { get; set; }
        public byte ExcludedRoleID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldPromotionCommittee
    {
        public int ApplicationID { get; set; }
        public Nullable<bool> isKFUPM { get; set; }
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Rank { get; set; }
        public string Email { get; set; }
        public string MailingAddress { get; set; }
        public string Major { get; set; }
        public int id { get; set; }
        public string Phone { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermanentCommittee
    {
        public int PermanentCommitteeTypeID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> ExternalEmployeeID { get; set; }
        public int PermanentCommitteeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ExternalEmployee ExternalEmployee { get; set; }
        public virtual PermanentCommitteeType PermanentCommitteeType { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermanentCommitteeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermanentCommitteeType()
        {
            this.PermanentCommittees = new HashSet<PermanentCommittee>();
        }
    
        public string Title { get; set; }
        public int PermanentCommitteeTypeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermanentCommittee> PermanentCommittees { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phase()
        {
            this.ActionMessages = new HashSet<ActionMessage>();
            this.Tasks = new HashSet<Task>();
            this.WFActions = new HashSet<WFAction>();
        }
    
        public byte PhaseID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<bool> IsCommittee { get; set; }
        public Nullable<bool> HasChair { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<bool> IsPermanentCommittee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionMessage> ActionMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAction> WFActions { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicationsEvaluation
    {
        public int ApplicationID { get; set; }
        public int ExternalReviewerID { get; set; }
        public int Form_AttachmentID { get; set; }
        public Nullable<int> EvaluationMark { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Form_AttachmentAd Form_AttachmentAd { get; set; }
        public virtual PublicationsEvaluation PublicationsEvaluation1 { get; set; }
        public virtual PublicationsEvaluation PublicationsEvaluation2 { get; set; }
        public virtual ExternalReviewer ExternalReviewer { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemindersFreeze
    {
        public int PeriodID { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportParameter
    {
        public byte ReportID { get; set; }
        public byte RoleID { get; set; }
        public string Parameter { get; set; }
        public string Value { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.Application_Role = new HashSet<Application_Role>();
            this.Departments = new HashSet<Department>();
            this.Form_AttachmentAd = new HashSet<Form_AttachmentAd>();
            this.NameExclusions = new HashSet<NameExclusion>();
            this.NameExclusions1 = new HashSet<NameExclusion>();
            this.ReportParameters = new HashSet<ReportParameter>();
            this.Task_Ext = new HashSet<Task_Ext>();
            this.Tasks = new HashSet<Task>();
            this.RolesReplacements = new HashSet<RolesReplacement>();
            this.RolesReplacements1 = new HashSet<RolesReplacement>();
            this.SpecialCases = new HashSet<SpecialCase>();
            this.SpecialCases1 = new HashSet<SpecialCase>();
        }
    
        public byte RoleID { get; set; }
        public string Title { get; set; }
        public byte Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Role> Application_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_AttachmentAd> Form_AttachmentAd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NameExclusion> NameExclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NameExclusion> NameExclusions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportParameter> ReportParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Ext> Task_Ext { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesReplacement> RolesReplacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesReplacement> RolesReplacements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialCase> SpecialCases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialCase> SpecialCases1 { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesReplacement
    {
        public int CaseID { get; set; }
        public byte RoleID { get; set; }
        public byte ReplacementRoleID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Status { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual SpecialCase SpecialCase { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentEmail
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string ToEmail { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string FromEmail { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecialCase()
        {
            this.RolesReplacements = new HashSet<RolesReplacement>();
        }
    
        public int CaseID { get; set; }
        public Nullable<byte> RoleID { get; set; }
        public Nullable<byte> EquivalentRoleID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Status { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Role Role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesReplacement> RolesReplacements { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagram
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.ActionMessages = new HashSet<ActionMessage>();
            this.Application_TaskForm = new HashSet<Application_TaskForm>();
            this.WFActions = new HashSet<WFAction>();
            this.WFActions1 = new HashSet<WFAction>();
            this.Task_Dependencies = new HashSet<Task_Dependencies>();
            this.Task_Dependencies1 = new HashSet<Task_Dependencies>();
            this.TaskForms = new HashSet<TaskForm>();
            this.Application_TaskLog = new HashSet<Application_TaskLog>();
        }
    
        public int TaskID { get; set; }
        public byte PhaseID { get; set; }
        public byte RoleID { get; set; }
        public string Title { get; set; }
        public Nullable<byte> RemindAfter { get; set; }
        public Nullable<byte> RemindAgainAfter { get; set; }
        public Nullable<bool> ActionRequired { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionMessage> ActionMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskForm> Application_TaskForm { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAction> WFActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAction> WFActions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Dependencies> Task_Dependencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Dependencies> Task_Dependencies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskForm> TaskForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskLog> Application_TaskLog { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Dependencies
    {
        public Nullable<int> ParentTaskID { get; set; }
        public Nullable<int> ChildTaskID { get; set; }
        public int TaskDependencyID { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Task Task1 { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Ext
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_Ext()
        {
            this.Application_TaskFormExt = new HashSet<Application_TaskFormExt>();
            this.Application_TaskLogExt = new HashSet<Application_TaskLogExt>();
            this.Task_ExtMessages = new HashSet<Task_ExtMessages>();
        }
    
        public int TaskID { get; set; }
        public string Title { get; set; }
        public Nullable<byte> RemindAfter { get; set; }
        public Nullable<byte> RemindAgainAfter { get; set; }
        public byte RoleID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskFormExt> Application_TaskFormExt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskLogExt> Application_TaskLogExt { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ExtMessages> Task_ExtMessages { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ExtMessages
    {
        public int TaskID { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Task_Ext Task_Ext { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskForm
    {
        public int TaskID { get; set; }
        public byte FormID { get; set; }
        public Nullable<byte> Rank { get; set; }
        public Nullable<byte> Level { get; set; }
        public string Instruction { get; set; }
        public bool Checkable { get; set; }
        public bool TaskExternal { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Task Task { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Reminders
    {
        public Nullable<int> ReminderNumber { get; set; }
        public Nullable<int> DaysPassed { get; set; }
        public int Reminders { get; set; }
        public Nullable<int> RemindersExpected { get; set; }
        public int TaskLogID { get; set; }
        public int ApplicationID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public string Message { get; set; }
        public Nullable<byte> RemindAfter { get; set; }
        public Nullable<byte> RemindAgainAfter { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFAction()
        {
            this.ActionMessages = new HashSet<ActionMessage>();
            this.Application_ActionStatus = new HashSet<Application_ActionStatus>();
            this.Application_Log = new HashSet<Application_Log>();
            this.WFAction1 = new HashSet<WFAction>();
            this.Application_TaskLog = new HashSet<Application_TaskLog>();
        }
    
        public int ActionID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<byte> NextPhaseID { get; set; }
        public Nullable<int> NextTaskID { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public Nullable<bool> RequireCompleteTask { get; set; }
        public string Status { get; set; }
        public Nullable<int> AttActionID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionMessage> ActionMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_ActionStatus> Application_ActionStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Log> Application_Log { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual Task Task { get; set; }
        public virtual Task Task1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAction> WFAction1 { get; set; }
        public virtual WFAction WFAction2 { get; set; }
        public virtual WFActionType WFActionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_TaskLog> Application_TaskLog { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFActionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFActionType()
        {
            this.WFActions = new HashSet<WFAction>();
        }
    
        public string Type { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAction> WFActions { get; set; }
    }
}
namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowAttribute
    {
        public int AttributeID { get; set; }
        public string Attribute { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
