//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FPSDBEntities : DbContext
    {
        public FPSDBEntities()
            : base("name=FPSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action_Log> Action_Log { get; set; }
        public virtual DbSet<ActionMessage> ActionMessages { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Application_ActionStatus> Application_ActionStatus { get; set; }
        public virtual DbSet<Application_Log> Application_Log { get; set; }
        public virtual DbSet<Application_LogExt> Application_LogExt { get; set; }
        public virtual DbSet<Application_Messages> Application_Messages { get; set; }
        public virtual DbSet<Application_Properties> Application_Properties { get; set; }
        public virtual DbSet<Application_Role> Application_Role { get; set; }
        public virtual DbSet<Application_TaskForm> Application_TaskForm { get; set; }
        public virtual DbSet<Application_TaskFormExt> Application_TaskFormExt { get; set; }
        public virtual DbSet<Application_TaskLogExt> Application_TaskLogExt { get; set; }
        public virtual DbSet<ApplicationChecklist> ApplicationChecklists { get; set; }
        public virtual DbSet<AttachmentCategory> AttachmentCategories { get; set; }
        public virtual DbSet<DeletedPromotionCommittee> DeletedPromotionCommittees { get; set; }
        public virtual DbSet<DepartmentManager> DepartmentManagers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeExt> EmployeeExts { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<ExternalEmployee> ExternalEmployees { get; set; }
        public virtual DbSet<ExtFormInstruction> ExtFormInstructions { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Form_AppProperties> Form_AppProperties { get; set; }
        public virtual DbSet<Form_AreaOfSp> Form_AreaOfSp { get; set; }
        public virtual DbSet<Form_Attachment> Form_Attachment { get; set; }
        public virtual DbSet<Form_AttachmentAd> Form_AttachmentAd { get; set; }
        public virtual DbSet<Form_ChairmanInput> Form_ChairmanInput { get; set; }
        public virtual DbSet<Form_Checklist> Form_Checklist { get; set; }
        public virtual DbSet<Form_CollegeInput> Form_CollegeInput { get; set; }
        public virtual DbSet<Form_DepartmentCommittee> Form_DepartmentCommittee { get; set; }
        public virtual DbSet<Form_ExtRev> Form_ExtRev { get; set; }
        public virtual DbSet<Form_FinalExtRev> Form_FinalExtRev { get; set; }
        public virtual DbSet<Form_FinalPC> Form_FinalPC { get; set; }
        public virtual DbSet<Form_FinalPromotionCommittee> Form_FinalPromotionCommittee { get; set; }
        public virtual DbSet<Form_FinalRefree> Form_FinalRefree { get; set; }
        public virtual DbSet<Form_MaterialFlag> Form_MaterialFlag { get; set; }
        public virtual DbSet<Form_MeetingMembers> Form_MeetingMembers { get; set; }
        public virtual DbSet<Form_Meetings> Form_Meetings { get; set; }
        public virtual DbSet<Form_PCFeedback> Form_PCFeedback { get; set; }
        public virtual DbSet<Form_PointChanges> Form_PointChanges { get; set; }
        public virtual DbSet<Form_Points> Form_Points { get; set; }
        public virtual DbSet<Form_PromotionCommittee> Form_PromotionCommittee { get; set; }
        public virtual DbSet<Form_PromotionReport> Form_PromotionReport { get; set; }
        public virtual DbSet<Form_Refree> Form_Refree { get; set; }
        public virtual DbSet<Form_ReviewersForm> Form_ReviewersForm { get; set; }
        public virtual DbSet<Form_ServiceYears> Form_ServiceYears { get; set; }
        public virtual DbSet<Form_Voting> Form_Voting { get; set; }
        public virtual DbSet<FormCategory> FormCategories { get; set; }
        public virtual DbSet<FormVariable> FormVariables { get; set; }
        public virtual DbSet<NameExclusion> NameExclusions { get; set; }
        public virtual DbSet<OldPromotionCommittee> OldPromotionCommittees { get; set; }
        public virtual DbSet<PermanentCommittee> PermanentCommittees { get; set; }
        public virtual DbSet<PermanentCommitteeType> PermanentCommitteeTypes { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<PublicationsEvaluation> PublicationsEvaluations { get; set; }
        public virtual DbSet<RemindersFreeze> RemindersFreezes { get; set; }
        public virtual DbSet<ReportParameter> ReportParameters { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SentEmail> SentEmails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Task_Dependencies> Task_Dependencies { get; set; }
        public virtual DbSet<Task_Ext> Task_Ext { get; set; }
        public virtual DbSet<Task_ExtMessages> Task_ExtMessages { get; set; }
        public virtual DbSet<TaskForm> TaskForms { get; set; }
        public virtual DbSet<WFAction> WFActions { get; set; }
        public virtual DbSet<WFActionType> WFActionTypes { get; set; }
        public virtual DbSet<WorkflowAttribute> WorkflowAttributes { get; set; }
        public virtual DbSet<Form_Feedback> Form_Feedback { get; set; }
        public virtual DbSet<vw_Reminders> vw_Reminders { get; set; }
        public virtual DbSet<ExternalReviewer> ExternalReviewers { get; set; }
        public virtual DbSet<RolesReplacement> RolesReplacements { get; set; }
        public virtual DbSet<SpecialCase> SpecialCases { get; set; }
        public virtual DbSet<Application_TaskLog> Application_TaskLog { get; set; }
    }
}
